### ISSUE TITLE
Documentation lacks information

### ISSUE THREAD

**Issue by frenetic** [stof/StofDoctrineExtensionsBundle#292] opened 2015-08-12 18:30 UTC
Hello all o/
First, thanks for the awesome effort :+1: 

Just installed this bundle to make use of **TimestampableEntity** trait.
I had a really hard time trying to make it work :crying_cat_face:

Documentation provided on https://github.com/stof/StofDoctrineExtensionsBundle/blob/master/Resources/doc/index.rst was not clear enough.

It took me almost an hour to discover I had to put the following piece of code on my ``config.yml``
```yaml
stof_doctrine_extensions:
    orm:
        default:
            timestampable: true
```

Please, add this information to the documentation.
Also, please, revalidate the documentation to check if there are something else missing.

**Comment by djhojd** [comment] 2015-08-23 19:55
@frenetic thank you, thank you, thank you! I also wasted ~1h but did not managed to figure this one out.
:+1: I also belive that docs need some revalidation.

**Comment by stwe** [comment] 2015-09-06 13:00
:+1: 

I also wasted many hours

http://stackoverflow.com/questions/30056402/configure-blameable-doctrine-extension-with-symfony2

    stof_doctrine_extensions:
        orm:
            default:
                blameable: true

**Comment by dstollie** [comment] 2015-09-08 08:28
So many hours, 2 hours for me!

**Comment by erikaheidi** [comment] 2015-09-10 17:37
The problem is that the `index.rst` doc is using some special formatting that doesn't render the configuration examples on GitHub :/ they are there, if you look in the raw file. Not sure what happened, cause I used this before and the docs where complete. Same problem on #294 and #293

**Comment by ruscon** [comment] 2015-11-18 12:07
+1 :(

**Comment by stof** [comment] 2015-11-24 09:50
The documentation is now rendered on http://symfony.com/doc/master/bundles/StofDoctrineExtensionsBundle/index.html

code snippets were missing because the doc was prepared for deployment on symfony.com (using rST features not supported by the github renderer) but not deployed yet. This is now fixed. The readme now links to the symfony.com website

**Closed by stof** 2015-11-24 09:50 UTC

**Comment by frenetic** [comment] 2015-11-25 20:59
Thank you @stof !
